#!/bin/bash
./test.sh "-i test_ptrn_grep.txt test_1_grep.txt"
./test.sh "-i While test_1_grep.txt"
./test.sh "-i test_ptrn_grep.txt test_2_grep.txt"
./test.sh "-i test_ptrn_grep.txt test_3_grep.txt"
./test.sh "-i test_ptrn_grep.txt test_4_grep.txt"
./test.sh "-i test_ptrn_grep.txt test_5_grep.txt"
./test.sh "-i test_ptrn_grep.txt test_6_grep.txt"
./test.sh "} test_1_grep.txt"
./test.sh "} test_2_grep.txt"
./test.sh "} test_3_grep.txt"
./test.sh "int test_4_grep.txt"
./test.sh "} test_5_grep.txt"
./test.sh "} test_6_grep.txt"
./test.sh "-e while -e str test_1_grep.txt -e int -e cmp"
./test.sh "-i -e str test_1_grep.txt -e int -e cmp"
./test.sh "-i -e str test_2_grep.txt -e int -e cmp"
./test.sh "-i -e str test_3_grep.txt -e int -e cmp"
./test.sh "-i -e str test_4_grep.txt -e int -e cmp"
./test.sh "-i -e str test_5_grep.txt -e int -e cmp -e Earth"
./test.sh "-i -e str test_6_grep.txt -e int -e cmp -e Earth"
./test.sh "-ei test_1_grep.txt"
./test.sh "-ei test_2_grep.txt"
./test.sh "-ei test_3_grep.txt"
./test.sh "-ei test_4_grep.txt"
./test.sh "-ei test_5_grep.txt"
./test.sh "-ei test_6_grep.txt"
./test.sh "-ie While test_1_grep.txt"
./test.sh "-f test_ptrn_grep.txt test_1_grep.txt"
./test.sh "-f test_ptrn_grep.txt test_1_grep.txt -i -c"
./test.sh "-f test_ptrn_grep.txt test_1_grep.txt -e str"
./test.sh "-f test_ptrn_grep.txt test_1_grep.txt -e Str -i"
./test.sh "-cf test_ptrn_grep.txt test_6_grep.txt -e Earth -i"
./test.sh "-icf test_ptrn_grep.txt test_1_grep.txt -e Str"
./test.sh "-vicl test_1_grep.txt -e int -e Earth"
./test.sh "-v -i -c -l test_1_grep.txt -e int -e Earth"
./test.sh "-v ephemeral test_6_grep.txt -l"
./test.sh "-v ephemeral test_6_grep.txt -c"
./test.sh "-v ephemeral test_6_grep.txt -lc"
./test.sh "-v test_6_grep.txt -l -e ephemeral"
./test.sh "-v test_6_grep.txt -e prince"
./test.sh "-f test_ptrn_grep.txt test_1_grep.txt -l"
./test.sh "-n int test_4_grep.txt"
./test.sh "-n str test_1_grep.txt"
./test.sh "-n while test_2_grep.txt"
./test.sh "-n $ test_3_grep.txt"
./test.sh "-n earth test_6_grep.txt"
./test.sh "-n int test_5_grep.txt"
./test.sh "-n -l int test_4_grep.txt"
./test.sh "-n -l str test_1_grep.txt"
./test.sh "-n -l while test_2_grep.txt"
./test.sh "-n -l $ test_3_grep.txt"
./test.sh "-n -l earth test_6_grep.txt"
./test.sh "-n -l int test_5_grep.txt"
./test.sh "-n -c int test_4_grep.txt"
./test.sh "-n -c str test_1_grep.txt"
./test.sh "-n -c while test_2_grep.txt"
./test.sh "-n -c $ test_3_grep.txt"
./test.sh "-n -c earth test_6_grep.txt"
./test.sh "-n -c int test_5_grep.txt"
./test.sh "-n -v str test_1_grep.txt"
./test.sh "-n -v while test_2_grep.txt"
./test.sh "-n -v $ test_3_grep.txt"
./test.sh "-n -v int test_4_grep.txt"
./test.sh "-n -v int test_5_grep.txt"
./test.sh "-n -v earth test_6_grep.txt"
./test.sh "-n -i str test_1_grep.txt"
./test.sh "-n -i while test_2_grep.txt"
./test.sh "-n -i $ test_3_grep.txt"
./test.sh "-n -i int test_4_grep.txt"
./test.sh "-n -i int test_5_grep.txt"
./test.sh "-n -i earth test_6_grep.txt"
./test.sh "-n -f test_ptrn_grep.txt test_1_grep.txt"
./test.sh "-n -f test_ptrn_grep.txt test_2_grep.txt"
./test.sh "-n -f test_ptrn_grep.txt test_3_grep.txt"
./test.sh "-n -f test_ptrn_grep.txt test_4_grep.txt"
./test.sh "-n -f test_ptrn_grep.txt test_5_grep.txt"
./test.sh "-n -f test_ptrn_grep.txt test_6_grep.txt"
./test.sh "-n -e str test_1_grep.txt"
./test.sh "-n -e while test_2_grep.txt"
./test.sh "-n -e $ test_3_grep.txt"
./test.sh "-n -e int test_4_grep.txt"
./test.sh "-n -e int test_5_grep.txt"
./test.sh "-n -e earth test_6_grep.txt"
./test.sh "-n -i -e str test_1_grep.txt"
./test.sh "-n -i -e while test_2_grep.txt"
./test.sh "-n -i -e $ test_3_grep.txt"
./test.sh "-n -i -e int test_4_grep.txt"
./test.sh "-n -i -e int test_5_grep.txt"
./test.sh "-n -i -e earth test_6_grep.txt"
./test.sh "-h str test_1_grep.txt test_ptrn_grep.txt"
./test.sh "-h while test_2_grep.txt test_ptrn_grep.txt"
./test.sh "-h $ test_3_grep.txt test_ptrn_grep.txt"
./test.sh "-h int test_4_grep.txt test_ptrn_grep.txt"
./test.sh "-h int test_5_grep.txt test_ptrn_grep.txt"
./test.sh "-h earth test_6_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -v -n -e str -f test_ptrn_grep.txt test_1_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -v -n -e while -f test_ptrn_grep.txt test_2_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -v -n -f test_ptrn_grep.txt -e $ test_3_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -v -n -f test_ptrn_grep.txt -e int test_4_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -v -n -f test_ptrn_grep.txt -e int test_5_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -v -n -f test_ptrn_grep.txt -e earth test_6_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -n -e str -f test_ptrn_grep.txt test_1_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -n -e while -f test_ptrn_grep.txt test_2_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -n -f test_ptrn_grep.txt -e $ test_3_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -n -f test_ptrn_grep.txt -e int test_4_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -n -f test_ptrn_grep.txt -e int test_5_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -n -f test_ptrn_grep.txt -e earth test_6_grep.txt test_ptrn_grep.txt"
./test.sh "-s .txt test_1_grep.txt test_ptrn_grep.txt"
./test.sh "-s sdf sd test_2_grep.txt test_ptrn_grep.txt"
./test.sh "-s t -e $ test_3_grep.txt test_ptrn_grep.txt"
./test.sh "-s .txt -e int test_4_grep.txt test_ptrn_grep.txt"
./test.sh "-s txt -e int test_5_grep.txt test_ptrn_grep.txt"
./test.sh "-s -l est_ptrn_grep.txt -e earth test_6_grep.txt test_ptrn_grep.txt"
./test.sh "-s -c .txt test_1_grep.txt test_ptrn_grep.txt"
./test.sh "-s -i sdf sd test_2_grep.txt test_ptrn_grep.txt"
./test.sh "-s -v t -e $ test_3_grep.txt test_ptrn_grep.txt"
./test.sh "-s -n .txt -e int test_4_grep.txt test_ptrn_grep.txt"
./test.sh "-s -h txt -e int test_5_grep.txt test_ptrn_grep.txt"
./test.sh "-s -v -h est_ptrn_grep.txt -e earth test_6_grep.txt tes"
./test.sh "-s -h txt -e int test_5_grep.txt test_ptrn_grep.txt -l"
./test.sh "-s -c .txt test_1_grep.txt test_ptrn_grep.txt"
./test.sh "-c while  test_1_grep.txt test_ptrn_grep.txt"
./test.sh "-e while  test_1_grep.txt test_ptrn_grep.txt txt -c"
# ./test.sh "-o int test_4_grep.txt -n"
# ./test.sh "-o int test_4_grep.txt -h"
# ./test.sh "-o int test_4_grep.txt dsd -s"
# ./test.sh "-o int test_4_grep.txt -l"
# ./test.sh "-o int test_4_grep.txt -e while -s"
# ./test.sh "-o int test_4_grep.txt -f test_ptrn_grep.txt"
# ./test.sh "-o inT test_4_grep.txt -i"
# ./test.sh "-o int test_4_grep.txt -c"
./test.sh "-i file.txt test.txt test2.txt"
./test.sh "-v file.txt test.txt test2.txt"
./test.sh "-c file.txt test.txt test2.txt"
./test.sh "-l file.txt test.txt test2.txt"
# ./test.sh "-o file.txt test.txt test2.txt"
./test.sh "-s file.txt test.txt test2.txt"
./test.sh "-h file.txt test.txt test2.txt"
./test.sh "-n file.txt test.txt test2.txt"
./test.sh "-i -i file.txt test.txt test2.txt"
./test.sh "-i -v file.txt test.txt test2.txt"
./test.sh "-i -c file.txt test.txt test2.txt"
./test.sh "-i -l file.txt test.txt test2.txt"
# ./test.sh "-i -o file.txt test.txt test2.txt"
./test.sh "-i -s file.txt test.txt test2.txt"
./test.sh "-i -h file.txt test.txt test2.txt"
./test.sh "-i -n file.txt test.txt test2.txt"
./test.sh "-v -i file.txt test.txt test2.txt"
./test.sh "-v -v file.txt test.txt test2.txt"
./test.sh "-v -c file.txt test.txt test2.txt"
./test.sh "-v -l file.txt test.txt test2.txt"
# ./test.sh "-v -o file.txt test.txt test2.txt"
./test.sh "-v -s file.txt test.txt test2.txt"
./test.sh "-v -h file.txt test.txt test2.txt"
./test.sh "-v -n file.txt test.txt test2.txt"
./test.sh "-c -i file.txt test.txt test2.txt"
./test.sh "-c -v file.txt test.txt test2.txt"
./test.sh "-c -c file.txt test.txt test2.txt"
./test.sh "-c -l file.txt test.txt test2.txt"
# ./test.sh "-c -o file.txt test.txt test2.txt"
./test.sh "-c -s file.txt test.txt test2.txt"
./test.sh "-c -h file.txt test.txt test2.txt"
./test.sh "-c -n file.txt test.txt test2.txt"
./test.sh "-l -i file.txt test.txt test2.txt"
./test.sh "-l -v file.txt test.txt test2.txt"
./test.sh "-l -c file.txt test.txt test2.txt"
./test.sh "-l -l file.txt test.txt test2.txt"
# ./test.sh "-l -o file.txt test.txt test2.txt"
./test.sh "-l -s file.txt test.txt test2.txt"
./test.sh "-l -h file.txt test.txt test2.txt"
./test.sh "-l -n file.txt test.txt test2.txt"
# ./test.sh "-o -i file.txt test.txt test2.txt"
# ./test.sh "-o -v file.txt test.txt test2.txt"
# ./test.sh "-o -c file.txt test.txt test2.txt"
# ./test.sh "-o -l file.txt test.txt test2.txt"
# ./test.sh "-o -o file.txt test.txt test2.txt"

# ./test.sh "-o -s file.txt test.txt test2.txt"

# ./test.sh "-o -h file.txt test.txt test2.txt"

# ./test.sh "-o -n file.txt test.txt test2.txt"

./test.sh "-s -i file.txt test.txt test2.txt"

./test.sh "-s -v file.txt test.txt test2.txt"

./test.sh "-s -c file.txt test.txt test2.txt"

./test.sh "-s -l file.txt test.txt test2.txt"

# ./test.sh "-s -o file.txt test.txt test2.txt"

./test.sh "-s -s file.txt test.txt test2.txt"

./test.sh "-s -h file.txt test.txt test2.txt"

./test.sh "-s -n file.txt test.txt test2.txt"

./test.sh "-h -i file.txt test.txt test2.txt"

./test.sh "-h -v file.txt test.txt test2.txt"

./test.sh "-h -c file.txt test.txt test2.txt"

./test.sh "-h -l file.txt test.txt test2.txt"

# ./test.sh "-h -o file.txt test.txt test2.txt"

./test.sh "-h -s file.txt test.txt test2.txt"

./test.sh "-h -h file.txt test.txt test2.txt"

./test.sh "-h -n file.txt test.txt test2.txt"

./test.sh "-n -i file.txt test.txt test2.txt"

./test.sh "-n -v file.txt test.txt test2.txt"

./test.sh "-n -c file.txt test.txt test2.txt"

./test.sh "-n -l file.txt test.txt test2.txt"

# ./test.sh "-n -o file.txt test.txt test2.txt"

./test.sh "-n -s file.txt test.txt test2.txt"

./test.sh "-n -h file.txt test.txt test2.txt"

./test.sh "-n -n file.txt test.txt test2.txt"

./test.sh "-i -e Hello file.txt test.txt test2.txt"

./test.sh "-v -e Hello file.txt test.txt test2.txt"

./test.sh "-c -e Hello file.txt test.txt test2.txt"

./test.sh "-l -e Hello file.txt test.txt test2.txt"

# ./test.sh "-o -e Hello file.txt test.txt test2.txt"

./test.sh "-s -e Hello file.txt test.txt test2.txt"

./test.sh "-h -e Hello file.txt test.txt test2.txt"

./test.sh "-n -e Hello file.txt test.txt test2.txt"

./test.sh "-i -f file.txt test.txt test2.txt"

./test.sh "-v -f file.txt test.txt test2.txt"

./test.sh "-c -f file.txt test.txt test2.txt"

./test.sh "-l -f file.txt test.txt test2.txt"

# ./test.sh "-o -f file.txt test.txt test2.txt"

