
./test.sh "-i test_ptrn_grep.txt test_1_grep.txt"
./test.sh "-i While test_1_grep.txt"
./test.sh "-i test_ptrn_grep.txt test_2_grep.txt"
./test.sh "-i test_ptrn_grep.txt test_3_grep.txt"
./test.sh "-i test_ptrn_grep.txt test_4_grep.txt"
./test.sh "-i test_ptrn_grep.txt test_5_grep.txt"
./test.sh "-i test_ptrn_grep.txt test_6_grep.txt"
./test.sh "} test_1_grep.txt"
./test.sh "} test_2_grep.txt"
./test.sh "} test_3_grep.txt"
./test.sh "int test_4_grep.txt"
./test.sh "} test_5_grep.txt"
./test.sh "} test_6_grep.txt"
./test.sh "-e while -e str test_1_grep.txt -e int -e cmp"
./test.sh "-i -e str test_1_grep.txt -e int -e cmp"
./test.sh "-i -e str test_2_grep.txt -e int -e cmp"
./test.sh "-i -e str test_3_grep.txt -e int -e cmp"
./test.sh "-i -e str test_4_grep.txt -e int -e cmp"
./test.sh "-i -e str test_5_grep.txt -e int -e cmp -e Earth"
./test.sh "-i -e str test_6_grep.txt -e int -e cmp -e Earth"
./test.sh "-ei test_1_grep.txt"
./test.sh "-ei test_2_grep.txt"
./test.sh "-ei test_3_grep.txt"
./test.sh "-ei test_4_grep.txt"
./test.sh "-ei test_5_grep.txt"
./test.sh "-ei test_6_grep.txt"
./test.sh "-ie While test_1_grep.txt"
./test.sh "-f test_ptrn_grep.txt test_1_grep.txt"
./test.sh "-f test_ptrn_grep.txt test_1_grep.txt -i -c"
./test.sh "-f test_ptrn_grep.txt test_1_grep.txt -e str"
./test.sh "-f test_ptrn_grep.txt test_1_grep.txt -e Str -i"
./test.sh "-cf test_ptrn_grep.txt test_6_grep.txt -e Earth -i"
./test.sh "-icf test_ptrn_grep.txt test_1_grep.txt -e Str"
./test.sh "-vicl test_1_grep.txt -e int -e Earth"
./test.sh "-v -i -c -l test_1_grep.txt -e int -e Earth"
./test.sh "-v ephemeral test_6_grep.txt -l"
./test.sh "-v ephemeral test_6_grep.txt -c"
./test.sh "-v ephemeral test_6_grep.txt -lc"
./test.sh "-v test_6_grep.txt -l -e ephemeral"
./test.sh "-v test_6_grep.txt -e prince"
./test.sh "-f test_ptrn_grep.txt test_1_grep.txt -l"
./test.sh "-n int test_4_grep.txt"
./test.sh "-n str test_1_grep.txt"
./test.sh "-n while test_2_grep.txt"
./test.sh "-n $ test_3_grep.txt"
./test.sh "-n earth test_6_grep.txt"
./test.sh "-n int test_5_grep.txt"
./test.sh "-n -l int test_4_grep.txt"
./test.sh "-n -l str test_1_grep.txt"
./test.sh "-n -l while test_2_grep.txt"
./test.sh "-n -l $ test_3_grep.txt"
./test.sh "-n -l earth test_6_grep.txt"
./test.sh "-n -l int test_5_grep.txt"
./test.sh "-n -c int test_4_grep.txt"
./test.sh "-n -c str test_1_grep.txt"
./test.sh "-n -c while test_2_grep.txt"
./test.sh "-n -c $ test_3_grep.txt"
./test.sh "-n -c earth test_6_grep.txt"
./test.sh "-n -c int test_5_grep.txt"
./test.sh "-n -v str test_1_grep.txt"
./test.sh "-n -v while test_2_grep.txt"
./test.sh "-n -v $ test_3_grep.txt"
./test.sh "-n -v int test_4_grep.txt"
./test.sh "-n -v int test_5_grep.txt"
./test.sh "-n -v earth test_6_grep.txt"
./test.sh "-n -i str test_1_grep.txt"
./test.sh "-n -i while test_2_grep.txt"
./test.sh "-n -i $ test_3_grep.txt"
./test.sh "-n -i int test_4_grep.txt"
./test.sh "-n -i int test_5_grep.txt"
./test.sh "-n -i earth test_6_grep.txt"
./test.sh "-n -f test_ptrn_grep.txt test_1_grep.txt"
./test.sh "-n -f test_ptrn_grep.txt test_2_grep.txt"
./test.sh "-n -f test_ptrn_grep.txt test_3_grep.txt"
./test.sh "-n -f test_ptrn_grep.txt test_4_grep.txt"
./test.sh "-n -f test_ptrn_grep.txt test_5_grep.txt"
./test.sh "-n -f test_ptrn_grep.txt test_6_grep.txt"
./test.sh "-n -e str test_1_grep.txt"
./test.sh "-n -e while test_2_grep.txt"
./test.sh "-n -e $ test_3_grep.txt"
./test.sh "-n -e int test_4_grep.txt"
./test.sh "-n -e int test_5_grep.txt"
./test.sh "-n -e earth test_6_grep.txt"
./test.sh "-n -i -e str test_1_grep.txt"
./test.sh "-n -i -e while test_2_grep.txt"
./test.sh "-n -i -e $ test_3_grep.txt"
./test.sh "-n -i -e int test_4_grep.txt"
./test.sh "-n -i -e int test_5_grep.txt"
./test.sh "-n -i -e earth test_6_grep.txt"
./test.sh "-h str test_1_grep.txt test_ptrn_grep.txt"
./test.sh "-h while test_2_grep.txt test_ptrn_grep.txt"
./test.sh "-h $ test_3_grep.txt test_ptrn_grep.txt"
./test.sh "-h int test_4_grep.txt test_ptrn_grep.txt"
./test.sh "-h int test_5_grep.txt test_ptrn_grep.txt"
./test.sh "-h earth test_6_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -v -n -e str -f test_ptrn_grep.txt test_1_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -v -n -e while -f test_ptrn_grep.txt test_2_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -v -n -f test_ptrn_grep.txt -e $ test_3_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -v -n -f test_ptrn_grep.txt -e int test_4_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -v -n -f test_ptrn_grep.txt -e int test_5_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -v -n -f test_ptrn_grep.txt -e earth test_6_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -n -e str -f test_ptrn_grep.txt test_1_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -n -e while -f test_ptrn_grep.txt test_2_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -n -f test_ptrn_grep.txt -e $ test_3_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -n -f test_ptrn_grep.txt -e int test_4_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -n -f test_ptrn_grep.txt -e int test_5_grep.txt test_ptrn_grep.txt"
./test.sh "-h -i -n -f test_ptrn_grep.txt -e earth test_6_grep.txt test_ptrn_grep.txt"


