#!/bin/bash

./test.sh "test_1_cat.txt"
./test.sh "test_2_cat.txt"
./test.sh "test_3_cat.txt"
./test.sh "test_4_cat.txt"
./test.sh "test_5_cat.txt"
./test.sh "test_case_cat.txt"
./test.sh "no_file.txt"

./test.sh "-b test_1_cat.txt"
./test.sh "-b test_2_cat.txt"
./test.sh "-b test_3_cat.txt"
./test.sh "-b test_4_cat.txt"
./test.sh "-b test_5_cat.txt"
./test.sh "-b test_case_cat.txt"

./test.sh "-n test_1_cat.txt"
./test.sh "-n test_2_cat.txt"
./test.sh "-n test_3_cat.txt"
./test.sh "-n test_4_cat.txt"
./test.sh "-n test_5_cat.txt"
./test.sh "-n test_case_cat.txt"

./test.sh "test_1_cat.txt test_2_cat.txt"
./test.sh "test_1_cat.txt test_2_cat.txt test_3_cat.txt"
./test.sh "test_1_cat.txt test_2_cat.txt test_3_cat.txt test_4_cat.txt"
./test.sh "test_1_cat.txt test_2_cat.txt test_3_cat.txt test_4_cat.txt test_5_cat.txt"
./test.sh "test_1_cat.txt test_2_cat.txt test_3_cat.txt test_4_cat.txt test_5_cat.txt test_case_cat.txt"

./test.sh "-v test_1_cat.txt"
./test.sh "-v test_2_cat.txt"
./test.sh "-v test_3_cat.txt"
./test.sh "-v test_4_cat.txt"
./test.sh "-v test_5_cat.txt"
./test.sh "-v test_case_cat.txt"

./test.sh "-s test_1_cat.txt"
./test.sh "-s test_2_cat.txt"
./test.sh "-s test_3_cat.txt"
./test.sh "-s test_4_cat.txt"
./test.sh "-s test_5_cat.txt"
./test.sh "-s test_case_cat.txt"

./test.sh "-t test_1_cat.txt"
./test.sh "-t test_2_cat.txt"
./test.sh "-t test_3_cat.txt"
./test.sh "-t test_4_cat.txt"
./test.sh "-t test_5_cat.txt"
./test.sh "-t test_case_cat.txt"

./test.sh "-e test_1_cat.txt"
./test.sh "-e test_2_cat.txt"
./test.sh "-e test_3_cat.txt"
./test.sh "-e test_4_cat.txt"
./test.sh "-e test_5_cat.txt"
./test.sh "-e test_case_cat.txt"

./test.sh "-E test_1_cat.txt"
./test.sh "-E test_2_cat.txt"
./test.sh "-E test_3_cat.txt"
./test.sh "-E test_4_cat.txt"
./test.sh "-E test_5_cat.txt"
./test.sh "-E test_case_cat.txt"

./test.sh "-T test_1_cat.txt"
./test.sh "-T test_2_cat.txt"
./test.sh "-T test_3_cat.txt"
./test.sh "-T test_4_cat.txt"
./test.sh "-T test_5_cat.txt"
./test.sh "-T test_case_cat.txt"

./test.sh "--number-nonblank test_case_cat.txt"
./test.sh "--number test_case_cat.txt"
./test.sh "--squeeze-blank test_case_cat.txt"

./test.sh "-benstvET test_1_cat.txt"
./test.sh "-benstvET test_2_cat.txt"
./test.sh "-benstvET test_3_cat.txt"
./test.sh "-benstvET test_4_cat.txt"
./test.sh "-benstvET test_5_cat.txt"
./test.sh "-benstvET test_case_cat.txt"